In [6]:
import numpy as np
import pandas as pd
import random

np.random.seed(38496905)
df = pd.DataFrame()
df["customer_id"] = np.random.randint(1,40, size=200)
categories = ("electronics","clothing","books","foods")
df["category"] = np.random.choice(categories, size=200)
prices = np.random.normal(50,15,200)
while prices.any() < 0:
    prices = np.random.normal(50,15,200)
df["price"] = prices.round(2)
df["quantity"] = np.random.randint(1,5,200)
discounts = (0,0.1,0.2)
df["discount"] = np.random.choice(discounts, size=200)
df["day"] = np.random.randint(1,30,200)
df

     customer_id     category  price  quantity  discount  day
0              3     clothing  59.71         3       0.2    2
1             28        foods  20.67         3       0.2   17
2             14     clothing  41.31         2       0.1   29
3             30  electronics  30.36         3       0.1   24
4              3     clothing  51.74         4       0.1   17
..           ...          ...    ...       ...       ...  ...
195            5  electronics  21.32         2       0.1   25
196           33  electronics  62.45         1       0.1   18
197            8        books  55.86         4       0.2    4
198           23  electronics  31.81         3       0.1   19
199           21        foods  28.63         3       0.2   27

[200 rows x 6 columns]

In [2]:
df["gross_revenue"] = df["price"] * df["quantity"]
df["net_revenue"] = (df["gross_revenue"] * (1 - df["discount"])).round(2)
df["category_avg_net_revenue"] = df.groupby(by = "category")["net_revenue"].transform("mean").round(2)
df[df["net_revenue"] > df["category_avg_net_revenue"]]

,customer_id,category,price,quantity,discount,day,gross_revenue,net_revenue,category_avg_net_revenue
0,3,clothing,59.71,3,0.2,2,179.13,143.30,120.28
4,3,clothing,51.74,4,0.1,17,206.96,186.26,120.28
5,6,books,48.71,4,0.2,19,194.84,155.87,123.94
6,14,books,50.76,3,0.0,22,152.28,152.28,123.94
8,30,foods,63.66,3,0.2,27,190.98,152.78,101.15
...,...,...,...,...,...,...,...,...,...
187,1,clothing,67.30,4,0.2,5,269.20,215.36,120.28
188,36,clothing,38.39,4,0.0,21,153.56,153.56,120.28
189,5,clothing,45.21,4,0.0,11,180.84,180.84,120.28
193,7,clothing,66.54,4,0.1,3,266.16,239.54,120.28
197,8,books,55.86,4,0.2,4,223.44,178.75,123.94

In [3]:
df.sample(7)

,customer_id,category,price,quantity,discount,day,gross_revenue,net_revenue,category_avg_net_revenue
84,27,foods,44.37,4,0.0,13,177.48,177.48,101.15
97,31,books,57.14,1,0.2,25,57.14,45.71,123.94
122,34,electronics,48.16,1,0.2,29,48.16,38.53,127.51
154,9,books,54.78,4,0.1,9,219.12,197.21,123.94
152,2,books,60.19,3,0.0,11,180.57,180.57,123.94
58,33,electronics,21.85,2,0.0,28,43.70,43.70,127.51
3,30,electronics,30.36,3,0.1,24,91.08,81.97,127.51

In [4]:
df.head(12)

,customer_id,category,price,quantity,discount,day,gross_revenue,net_revenue,category_avg_net_revenue
0,3,clothing,59.71,3,0.2,2,179.13,143.30,120.28
1,28,foods,20.67,3,0.2,17,62.01,49.61,101.15
2,14,clothing,41.31,2,0.1,29,82.62,74.36,120.28
3,30,electronics,30.36,3,0.1,24,91.08,81.97,127.51
4,3,clothing,51.74,4,0.1,17,206.96,186.26,120.28
5,6,books,48.71,4,0.2,19,194.84,155.87,123.94
6,14,books,50.76,3,0.0,22,152.28,152.28,123.94
7,21,foods,61.46,1,0.2,5,61.46,49.17,101.15
8,30,foods,63.66,3,0.2,27,190.98,152.78,101.15
9,19,foods,66.14,1,0.1,17,66.14,59.53,101.15
10,21,books,28.77,1,0.1,7,28.77,25.89,123.94
11,1,clothing,36.38,4,0.2,24,145.52,116.42,120.28

In [5]:
df["order_type"] = df.apply(lambda row: 
                            "bulk_discounted" if (row["quantity"] >= 4) & (row["discount"] > 0) else
                            "bulk_fullprice" if (row["quantity"] >= 4) & (row["discount"] == 0) else
                            "standard_discounted" if (row["discount"]>0) & (row["quantity"]<4) else 
                            "standard_fullprice",axis=1)
sum_table = pd.DataFrame({"average_price" : df.groupby(by = "category")["price"].agg("mean").round(2), 
                        "total_quantity" : df.groupby(by = "category")["quantity"].agg("sum"),
                        "average_discount" : df.groupby(by = "category")["discount"].agg("mean").round(2),
                         "total net revenue" : df.groupby(by = "category")["net_revenue"].agg("sum"),
                         "number of transactions" : df.groupby(by = "category").size()})
sum_table

,average_price,total_quantity,average_discount,total net revenue,number of transactions
category,,,,,
books,51.83,152,0.11,7188.76,58
clothing,49.72,116,0.12,5172.06,43
electronics,51.58,150,0.10,6885.71,54
foods,51.23,98,0.09,4551.81,45